config/routes.rb
Rails.application.routes.draw do
  constraints(id: /\d+/ ) do
    resources :users
    resources :projects do 
      resources :tickets do 
        member do
          get '/projects/related', to:'tickets#show_projects'
          get '/projects/related/add', to:'tickets#add_projects'
          put '/projects/related/add', to:'tickets#add_projects'
        end
      end
    end

    get '/tickets', to:'tickets#ticket_index'
    match  '/users/login', to:'users#login',via:[:get,:post]
    get '/users/logout', to:'users#logout'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence:true, on:[:create,:update]
  validates :email, presence:true, uniqueness:true,format:{with: /\A.+?@.+?\..+$\z/},on:[:create]
  validates :email, presence:true,format:{with: /\A.+?@.+?\..+$\z/},on:[:update]
  has_secure_password
  validates :password, presence:true,length:{in:6..50},on: [ :create]#,:update_password]  
  validates :password_confirmation, presence:true,on:[:create]
  before_save :lower_fields 
  has_many :tickets, foreign_key:"owner_id"
  has_many :project_logs, class_name:"ProjectLog"


  def manager?
    self.type == 'Manager'? true: false
  end

  protected 
    def lower_fields
      self.name = self.name.downcase
      self.email = self.email.downcase
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionCheck
  #Get /users 
  def index
    if session_exists?
      redirect_to user_path(session[:user_id]) 
    end
  end

  #Get /users/new
  def new
    if !session_exists?
      @user = User.new
    else 
      redirect_to user_path(session[:user_id])
    end
  end

  #Post /users
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:message] = "User successfully created"
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  #Get /users/:id
  def show
    if session_exists? 
      @user = User.find(session[:user_id])
    else 
      redirect_to users_login_path
    end
  end

  #Get /users/:id/edit
  def edit
    if session_exists?
      @user = User.find(session[:user_id])
    else 
      redirect_to users_login_path and return 
    end
  end

  #Put/Patch /users/:id
  def update
    @user = User.find(session[:user_id])
    email = user_edit_params[:email]
    if email != @user.email
      check_user = User.find_by_email(email)
      if check_user
        flash[:message] = "user with this email exists"
        redirect_to edit_user_path and return
      end
    end
    if @user.update(user_edit_params)
      redirect_to @user and return 
    else 
      redirect_to  edit_user_path(@user) and return 
    end
  end

  #Delete /users/:id
  def destroy
    if session_exists?
      @user = User.find_by(session[:user_id])
      @user.destroy
      session[:user_id] = nil
      redirect_to users_path
    end
  end

  #Post /users/login
  #Get /users/login
  def login
    if !session_exists?
      if request.request_method_symbol == :get 
        render "login"
      elsif request.request_method_symbol == :post
        email  =user_login_params[:email]
        password= user_login_params[:password]
        remember = user_login_params[:remember]
        @user = User.find_by_email(email)
        if !@user.nil? && @user.authenticate(password)
          digest = SecureRandom.urlsafe_base64
          @user.update(remember_digest:BCrypt::Password.create(digest)) if remember == '1'
          cookies.permanent.signed[:remember_token] = digest
          session[:user_id] = @user.id
          flash[:message] = nil
          redirect_to @user
        else 
          flash[:message] = "Email or password incorrect"
          render "login"
        end
      end
    else 
      redirect_to user_path(session[:user_id])
    end
  end

  #Get /users/logout
  def logout
    if session_exists?
      session.delete(:user_id)
      cookies.delete(:remember_token)
      redirect_to users_path
    end
  end

  private 
    def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation,:type)
    end

    def user_edit_params
      params.require(:user).permit(:name,:email,:type)
    end

    def user_login_params
      params.permit(:email,:password,:remember)
    end

    def not_found
      raise ActionController::RoutingError.new('Not Found')
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form_edit_user.html.erb
<%= form_for(@user) do |f|%>
  <p> 
  <%=  f.label :name%>:
  <%= f.text_field :name %>
  </p>
  <p>
  <%= f.label  :email%>:
  <%= f.text_field :email%>
  </p>
  <p>
  <%= f.label  :type,"Role" %>:
  <% Rails.application.eager_load! %>
  <%= f.select  :type,options_for_select(User.descendants.map(&:to_s),@user.type) %>
  </p>
  <p>
  <%= f.submit  %>
  </p>
<% end %>

app/views/users/_form_user.html.erb
<%= form_for(@user) do |f| %>

  <p><%= f.label :name %>: <%= f.text_field :name %> </p>
 

  <p><%= f.label :email %>:<%= f.email_field :email %></p>
  

  <p><%= f.label :password %>:<%= f.password_field :password %></p>
  
  <p>
  <%= f.label :password_confirmation %>:
  <%= f.password_field :password_confirmation %>
  </p>

  <p>
  <% Rails.application.eager_load! %> 
  <%= f.label :type %>
  <%= f.select :type,User.descendants.map(&:to_s) %>
  </p>

  <p><%= f.submit %></p>


<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<%= render "partials/flash_message" %>
<%= render "partials/error_validation",model:@user%>
<%= render "form_edit_user" %>

app/views/users/index.html.erb
<h1>Users#index</h1>

<%= link_to "Login",users_login_path %> or 
<%= link_to "Signup",new_user_path %>

app/views/users/login.html.erb
<h1>User#Login</h1>
<%= render "partials/flash_message" %>
<%=  form_tag  do %>
  <p>
  <%=  label_tag :email %>
  <%=  text_field_tag :email %> 
  </p>


  <p>  
  <%=  label_tag :password %>
  <%=  password_field_tag :password %>
  </p>

  <p>
    <span><%= check_box_tag 'remember' %></span>
    <span><%= label_tag :remember_me %></span>
  </p>
  
  <p>
  <%=  submit_tag :login %>
  </p>
<%  end %>

or
<%= link_to 'Signup',new_user_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= render "partials/error_validation",model:@user %>
<%= render "form_user" %>
or
<%= link_to "Login",users_login_path %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<%= render "partials/flash_message" %>
<p>Hi <%= @user.name %></p>

<p>
<%= link_to "Logout",users_logout_path %>
</p>
<p>
<%= link_to "Edit",edit_user_path %>
</p>
<p>
<%= link_to "Delete profile",user_path,method: :delete %>
</p>