config/routes.rb
Rails.application.routes.draw do
  constraints(id: /\d+/ ) do
    resources :users
    resources :projects do 
      resources :tickets do 
        member do
          get '/projects/related', to:'tickets#show_projects'
          get '/projects/related/add', to:'tickets#add_projects'
          put '/projects/related/add', to:'tickets#add_projects'
        end
      end
    end

    get '/tickets', to:'tickets#ticket_index'
    match  '/users/login', to:'users#login',via:[:get,:post]
    get '/users/logout', to:'users#logout'
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :manager
  belongs_to :user
  has_and_belongs_to_many :tickets
  has_and_belongs_to_many :developers,join_table:"developers_projects"
  validates :title, presence:true
  validates :manager, presence:true
  validates :user, presence:true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include SessionCheck

  around_action :session_action

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save 
      redirect_to @project
    else 
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project
    else 
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to projects_path
    else 
      render :show
    end
  end

  private 
    
    def project_params
      params.require(:project).permit(:title,:description,:planned_completion_date,:manager_id,:creator_id)
    end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form_project.html.erb
<%= form_for @project,url:projects_path do |f| %>
  <p>
  <%=  f.label :title %>
  <%= f.text_field :title %>
  </p>
  <p>
  <%= f.label :description %>
  <%= f.text_area :description %>
  </p>
  <p>
  <%= f.label :planned_completion_date %> 
  <%= f.date_field :planned_completion_date %>
  </p>
  <p>
  <%= f.label :manager_id %>
  <%= f.text_field :manager_id %>
  </p>
  <p>
  <%= f.label :creator_id %> 
  <%= f.text_field :creator_id %>
  </p>
  <p>
  <%= f.submit %>
  </p>
<%  end %>

app/views/projects/edit.html.erb
<h1>Project#edit</h1>
<%= render "partials/flash_message" %>
<%= render "partials/error_validation",model:@project%>
<%= render "form_project" %>

app/views/projects/index.html.erb
<h1>Project#index</h1>
<% @projects.each do |project| %>
  <p>
  <%= link_to project.title,project_path(project) %>
  </p>
<%   end %>

app/views/projects/new.html.erb
<h1>Project#new</h1>
<%=  render "partials/error_validation",model:@project %>
<%= render "form_project" %>

app/views/projects/show.html.erb
<h1>Project#show</h1>
<p>
<%= @project.title %>
</p>
<p>
<%=  @project.description %>
</p>

<p>
<%= link_to "All tickets",project_tickets_path(@project) %>
</p>
<p>
<%= link_to "Add ticket",new_project_ticket_path(@project) %>
</p>