config/routes.rb
Rails.application.routes.draw do
  constraints(id: /\d+/ ) do
    resources :users
    resources :projects do 
      resources :tickets do 
        member do
          get '/projects/related', to:'tickets#show_projects'
          get '/projects/related/add', to:'tickets#add_projects'
          put '/projects/related/add', to:'tickets#add_projects'
        end
      end
    end

    get '/tickets', to:'tickets#ticket_index'
    match  '/users/login', to:'users#login',via:[:get,:post]
    get '/users/logout', to:'users#logout'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IssueTrackingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  
  <a href=<%= session[:user_id] ? user_path(session[:user_id]) : users_login_path  %>>
    <%= image_tag("logo.png") %>
  </a>
  <% if !session[:user_id] %>
    <a href=<%= users_login_path %> class="btn btn-default navbar-btn navbar-right signin">SignUp/Login</a>
  <% else %>
    <a href=<%= projects_path %> class="btn btn-default navbar-btn projects">Projects</a>
    <a href=<%= tickets_path %> class="btn btn-default navbar-btn tickets">Tickets</a>
    <a href=<%= user_path(session[:user_id])%> class="btn btn-default navbar-btn navbar-right name"><%= User.find(session[:user_id]).name.split(' ').map{|x| x.capitalize}.join(' ') %></a>
  <% end %>
</nav>

<div class="container">
  <%= yield %>
</div>
<footer class="footer">
  <div class="container">
    <p class="text-muted">An issue tracking app</p>
  </div>
</footer>
</body>
</html>